# Generated by Django 5.2.4 on 2025-07-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_2026', models.IntegerField(blank=True, null=True)),
                ('rank_2025', models.IntegerField(blank=True, null=True)),
                ('institution_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('focus', models.CharField(max_length=10)),
                ('research_intensity', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('score_ar', models.FloatField(blank=True, null=True)),
                ('rank_ar', models.IntegerField(blank=True, null=True)),
                ('score_er', models.FloatField(blank=True, null=True)),
                ('rank_er', models.IntegerField(blank=True, null=True)),
                ('score_fs', models.FloatField(blank=True, null=True)),
                ('rank_fs', models.IntegerField(blank=True, null=True)),
                ('score_cpf', models.FloatField(blank=True, null=True)),
                ('rank_cpf', models.IntegerField(blank=True, null=True)),
                ('score_if', models.FloatField(blank=True, null=True)),
                ('rank_if', models.IntegerField(blank=True, null=True)),
                ('score_is', models.FloatField(blank=True, null=True)),
                ('rank_is', models.IntegerField(blank=True, null=True)),
                ('score_isd', models.FloatField(blank=True, null=True)),
                ('rank_isd', models.IntegerField(blank=True, null=True)),
                ('score_irn', models.FloatField(blank=True, null=True)),
                ('rank_irn', models.IntegerField(blank=True, null=True)),
                ('score_eo', models.FloatField(blank=True, null=True)),
                ('rank_eo', models.IntegerField(blank=True, null=True)),
                ('score_st', models.FloatField(blank=True, null=True)),
                ('rank_st', models.IntegerField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['rank_2026'],
            },
        ),
    ]
